apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: qatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo 
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - image: harbor.test.invsetoday.net/demo/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Always
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: s-j-qatest
   namespace: qatest
spec:
   selector:
     app: jenkins-demo
   type: ClusterIP
   ports:
   - port: 18888
     targetPort: 18888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-j-qatest
  namespace: qatest
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: j-qatest.test.investoday.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: s-j-qatest
            port:
              number: 18888

