apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: belbert/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
   name: s-j-prod
   namespace: prod
spec:
  selector:
    app: jenkins-demo
  type: ClusterIP
  ports:
  - port: 18888
    targetPort: 18888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-j-prod
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: j-prod.test.investoday.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: s-j-prod
            port:
              number: 18888
